/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RABIUL
 */
public class AdminCheckForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminCheckForm
     */
    String selectedDate = "", p_id = "";
    Connection conn;
    Statement statement1;
    ResultSet rs;

    public AdminCheckForm() {
        initComponents();
    }

    public AdminCheckForm(String selectedDate, String p_id) {
        selectedDate = selectedDate;
        p_id = p_id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_userName = new javax.swing.JTextField();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/minimize.png"))); // NOI18N
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });
        jPanel2.add(minimize_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/cancel.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        jTextField_userName.setText("Enter User Name");
        jTextField_userName.setBorder(null);
        jTextField_userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_userNameFocusGained(evt);
            }
        });
        jPanel3.add(jTextField_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 220, 20));

        jPasswordField_pass.setText("jPasswordField1");
        jPasswordField_pass.setBorder(null);
        jPasswordField_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passFocusGained(evt);
            }
        });
        jPasswordField_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_passKeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 220, 20));

        jLabel4.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setText("       Sign Up");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField_userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userNameFocusGained
        // TODO add your handling code here:
        jTextField_userName.setText("");
    }//GEN-LAST:event_jTextField_userNameFocusGained

    private void jPasswordField_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passFocusGained
        // TODO add your handling code here:
        jPasswordField_pass.setText("");
    }//GEN-LAST:event_jPasswordField_passFocusGained

    private void jPasswordField_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordField_passKeyPressed

    private void loginAction() {
        EncryptData encrypt = new EncryptData();

        String userName = jTextField_userName.getText();
        char[] pwd = jPasswordField_pass.getPassword();
        String password = encrypt.encryptPass(String.copyValueOf(pwd));

        String userType = "Admin";

        if (userName.length() < 1) {
            JOptionPane.showMessageDialog(null, "Please Provide valid User Name", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (password.length() < 1) {
            JOptionPane.showMessageDialog(null, "Please Provide valid Password", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Boolean isFound = SqlManager.loginUser(userName, password, userType);
            if (!isFound) {
                JOptionPane.showMessageDialog(null, "User Not Found", "User Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        SqlManager.getUserName();
        this.dispose();
        if (userType.equalsIgnoreCase("Admin")) {
            dispose();
            String qunatity_sell = "", qunatity_stock = "";
            conn = DBConnection.connectDb();
            if (conn != null) {
                try {
                    String query = "select * from sell where date = '" + selectedDate + "'";
                    statement1 = conn.createStatement();
                    rs = statement1.executeQuery(query);
                    while (rs.next()) {
                        qunatity_sell = rs.getString("quantity");
                    }
                    rs.close();
                    statement1.close();
                    String query_s = "select * from stock where date = '" + p_id + "'";
                    statement1 = conn.createStatement();
                    rs = statement1.executeQuery(query);
                    while (rs.next()) {
                        qunatity_stock = rs.getString("quantity");
                    }
                    rs.close();
                    statement1.close();

                    double total_quantity = Double.parseDouble(qunatity_stock) + Double.parseDouble(qunatity_sell);
                    
                    

                } catch (Exception e) {
                    e.printStackTrace();
                } finally {

                }
            } else {
                JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Failed!!!");
        }
    }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCheckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCheckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCheckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCheckForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCheckForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JTextField jTextField_userName;
    private javax.swing.JLabel minimize_label;
    // End of variables declaration//GEN-END:variables
}
