/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DeeptoTV
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minimize_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField_userName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        userError1 = new javax.swing.JLabel();
        errorPass = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/cancel.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Belwe Bd BT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 51));
        jLabel3.setText("LogicUnion POS Software");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 30));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/minimize.png"))); // NOI18N
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });
        jPanel2.add(minimize_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("          With");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

        jLabel10.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("         LogicUnion POS System");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 380, -1));

        jLabel11.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("         Improve Your Buiseness ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 410, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 410, 10));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/login1.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 350, 250));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 440, 480));

        jPanel4.setBackground(new java.awt.Color(0, 153, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, -1));

        jLabel5.setFont(new java.awt.Font("Belwe Bd BT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("No Admin?");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, -1));

        user_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee" }));
        jPanel4.add(user_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, -1));

        jLabel6.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel6.setText("User Type");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, -1));

        jTextField_userName.setText("Enter User Name");
        jTextField_userName.setBorder(null);
        jTextField_userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_userNameFocusGained(evt);
            }
        });
        jPanel4.add(jTextField_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 134, 300, 20));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, -1));

        userError.setForeground(new java.awt.Color(204, 0, 51));
        jPanel4.add(userError, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 250, -1));

        jLabel7.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel7.setText("User Name");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        jPasswordField_pass.setText("jPasswordField1");
        jPasswordField_pass.setBorder(null);
        jPasswordField_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passFocusGained(evt);
            }
        });
        jPasswordField_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_passKeyPressed(evt);
            }
        });
        jPanel4.add(jPasswordField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 300, 20));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 300, 10));

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setText("               Log In");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 210, 50));

        userError1.setForeground(new java.awt.Color(204, 0, 51));
        jPanel4.add(userError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 250, -1));

        errorPass.setForeground(new java.awt.Color(204, 0, 51));
        jPanel4.add(errorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, -1));

        jLabel13.setFont(new java.awt.Font("Belwe Bd BT", 0, 24)); // NOI18N
        jLabel13.setText("LOGIN");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 430, 480));

        jLabel1.setFont(new java.awt.Font("Belwe Bd BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Point Of Sales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField_userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userNameFocusGained
        // TODO add your handling code here:
        if(jPasswordField_pass.getText().length() == 0){
            errorPass.setText("Please Enter Password");
        }
        else{
            errorPass.setText("");
        }
        jTextField_userName.setText("");
    }//GEN-LAST:event_jTextField_userNameFocusGained

    private void jPasswordField_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passFocusGained
        // TODO add your handling code here:
        if(jTextField_userName.getText().length() == 0){
            userError.setText("Please Enter User Name");
        }
        else{
            userError.setText("");
        }
        jPasswordField_pass.setText("");
    }//GEN-LAST:event_jPasswordField_passFocusGained

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        loginAction();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void loginAction(){
        EncryptData encrypt = new EncryptData();
        
        String userName = jTextField_userName.getText();
        char[] pwd = jPasswordField_pass.getPassword();
        String password = encrypt.encryptPass(String.copyValueOf(pwd));
        
        String userType = user_type.getSelectedItem().toString();
        
        if(userName.length()<1){
            JOptionPane.showMessageDialog(null, "Please Provide valid User Name", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(password.length()<1){
            JOptionPane.showMessageDialog(null, "Please Provide valid Password", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
            try {
            Boolean isFound=SqlManager.loginUser(userName,password,userType);
            if(!isFound){
                JOptionPane.showMessageDialog(null, "User Not Found", "User Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        SqlManager.getUserName();
        this.dispose();
        String type = "";
        if(userType.equalsIgnoreCase("Admin")){
            
            dispose();
                HomeForm hf = new HomeForm(userType);
                hf.setLocation(100, 50);
                //hf.setResizable(false);
                hf.setVisible(true);
        }
        else{
            dispose();
                PointOfSaleForm_2 pos = new PointOfSaleForm_2(userType);
                //PointOfSaleForm pos = new PointOfSaleForm();
                pos.setVisible(true);
        }
        
    }
    
    
    
    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        AdminAddForm adminForm = new AdminAddForm();
        adminForm.setDefaultCloseOperation(adminForm.DISPOSE_ON_CLOSE);
        adminForm.setLocation(300, 250);
        adminForm.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPasswordField_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            loginAction();
        }
    }//GEN-LAST:event_jPasswordField_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField_userName;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JLabel userError;
    private javax.swing.JLabel userError1;
    private javax.swing.JComboBox<String> user_type;
    // End of variables declaration//GEN-END:variables
}
