/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RABIUL
 */
public class PointOfSaleForm extends javax.swing.JFrame {

    Connection conn = null;
    Statement statement1 = null;
    ResultSet rs = null;
    String userType = "";
    String selectedProduct = "";
    
    HashMap dataSet = new HashMap();
    double gross_total = 0;
    ArrayList selectedRowList = new ArrayList();
    Vector dataSetList = new Vector();

    /**
     * Creates new form PointOfSaleForm
     */
    public PointOfSaleForm() {
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minimize_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_sell_article = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_sell_description = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_sell_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_sell_total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_sell_unit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_sell_vat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_sell_date = new javax.swing.JTextField();
        jTextField_reciptNo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField_sell_product_id = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_sell_quantity = new javax.swing.JTextField();
        jTextField_sell_discount = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_stock = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_sell_gross_total = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton_sell_save = new javax.swing.JButton();
        jButton_sell_print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_sell = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/user_emp.png"))); // NOI18N
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 30, 20));

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rabiul");
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/cancel.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, -1, -1));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/minimize.png"))); // NOI18N
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });
        jPanel13.add(minimize_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company Name");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 160, 20));

        jLabel24.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/back.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setText("LogOut");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 40));

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/filter.png"))); // NOI18N
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        jPanel14.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 10));

        jTextField3.setBorder(null);
        jPanel14.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 20));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Article" }));
        jPanel14.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 110, -1));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/search.png"))); // NOI18N
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Article" }));
        jPanel14.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, -1));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1350, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Company Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 160, 20));
        jPanel2.add(jTextField_sell_article, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, -1));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Article");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 20));
        jPanel2.add(jTextField_sell_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, -1));

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 20));
        jPanel2.add(jTextField_sell_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, -1));

        jLabel9.setBackground(new java.awt.Color(204, 0, 0));
        jLabel9.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 20));

        jLabel10.setBackground(new java.awt.Color(204, 0, 0));
        jLabel10.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 60, 20));

        jTextField_sell_total.setEditable(false);
        jPanel2.add(jTextField_sell_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 200, -1));

        jLabel11.setBackground(new java.awt.Color(204, 0, 0));
        jLabel11.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quntity in buy");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 20));

        jTextField_sell_unit.setEditable(false);
        jPanel2.add(jTextField_sell_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 90, -1));

        jLabel12.setBackground(new java.awt.Color(204, 0, 0));
        jLabel12.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Discount");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, 20));

        jLabel14.setBackground(new java.awt.Color(204, 0, 0));
        jLabel14.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("%");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 60, 20));

        jTextField_sell_vat.setText("0");
        jTextField_sell_vat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sell_vatKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField_sell_vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, -1));

        jLabel15.setBackground(new java.awt.Color(204, 0, 0));
        jLabel15.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("VAT");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 60, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/add_btn.png"))); // NOI18N
        jButton1.setText("ADD");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 130, 40));

        jLabel16.setBackground(new java.awt.Color(204, 0, 0));
        jLabel16.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 20));
        jPanel2.add(jTextField_sell_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, -1));
        jPanel2.add(jTextField_reciptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 200, -1));

        jLabel25.setBackground(new java.awt.Color(204, 0, 0));
        jLabel25.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("RN#");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));
        jPanel2.add(jTextField_sell_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 200, -1));

        jLabel26.setBackground(new java.awt.Color(204, 0, 0));
        jLabel26.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Product ID");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 20));

        jTextField_sell_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sell_quantityKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField_sell_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, -1));

        jTextField_sell_discount.setText("0");
        jTextField_sell_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sell_discountKeyReleased(evt);
            }
        });
        jPanel2.add(jTextField_sell_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 80, -1));

        jLabel27.setBackground(new java.awt.Color(204, 0, 0));
        jLabel27.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("%");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 60, 20));
        jPanel2.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, -1));

        jLabel28.setBackground(new java.awt.Color(204, 0, 0));
        jLabel28.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Customer No");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 150, -1));

        jLabel29.setBackground(new java.awt.Color(204, 0, 0));
        jLabel29.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Previous Due");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 100, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 380, 420));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Products Available", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Stock", "Selling Price"
            }
        ));
        jTable_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_stockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_stock);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 210));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));
        jPanel7.add(jTextField_sell_gross_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 30));
        jPanel7.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 30));

        jLabel17.setBackground(new java.awt.Color(204, 0, 0));
        jLabel17.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Payment");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));
        jPanel7.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, 30));

        jLabel18.setBackground(new java.awt.Color(204, 0, 0));
        jLabel18.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Change");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit" }));
        jPanel7.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 20));

        jLabel19.setBackground(new java.awt.Color(204, 0, 0));
        jLabel19.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Payment Type");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 20));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 190));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_sell_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/save.png"))); // NOI18N
        jButton_sell_save.setText("jButton2");
        jPanel8.add(jButton_sell_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 80));

        jButton_sell_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/printer.jpg"))); // NOI18N
        jButton_sell_print.setText("jButton3");
        jPanel8.add(jButton_sell_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 70));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 130, 190));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 490, 210));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 960, 240));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Your Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_sell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recipt #", "Product ID", "Article", "Desc", "Unit Price", "Quantity", "Discount ", "VAT%", "Total", "Date", "Transaction Type"
            }
        ));
        jScrollPane2.setViewportView(jTable_sell);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 960, 310));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 960, 350));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, -1));

        jLabel20.setBackground(new java.awt.Color(204, 0, 0));
        jLabel20.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Recipt No");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));
        jPanel9.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, -1));

        jLabel21.setBackground(new java.awt.Color(204, 0, 0));
        jLabel21.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Article");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));
        jPanel9.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, -1));

        jLabel22.setBackground(new java.awt.Color(204, 0, 0));
        jLabel22.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Discount");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));
        jPanel9.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, -1));

        jLabel23.setBackground(new java.awt.Color(204, 0, 0));
        jLabel23.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Qty");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 180));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Remove from chart");
        jPanel10.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jButton5.setText("Cancel Transaction");
        jPanel10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 180));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 380, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
        LoginForm lf = new LoginForm();
        lf.setLocation(100, 50);
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        dispose();
        //LoginForm lf = new LoginForm();
        HomeForm lf = new HomeForm();
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginForm lf = new LoginForm();
        lf.setLocation(100, 50);
        lf.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        jButton_sell_print.setEnabled(false);
        //date
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calobj = Calendar.getInstance();
        jTextField_sell_date.setText(df.format(calobj.getTime()));

        //reciptNo generate
        SalesManager saleManager = new SalesManager();

        try {
            int reciptNo = saleManager.reciptNo();
            jTextField_reciptNo.setText(String.valueOf(reciptNo + 1));
        } catch (SQLException ex) {
            Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        String p_id = "", p_name = "", stock = "", s_price = "";
        Vector columnNames = new Vector();
        Vector data = new Vector();
        int columns = 0;
        String sql = "select * from stock";
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(sql);
                //this.jTable1.setModel(DbUtils.resultSetToTableModel(rs_razuna));

                columnNames.addElement("Product ID");
                columnNames.addElement("Product Name");
                columnNames.addElement("Stock");
                columnNames.addElement("Selling Price");

                while (rs.next()) {
                    Vector row = new Vector(columns);
                    p_id = rs.getString("product_id");
                    p_name = rs.getString("article");
                    stock = rs.getString("quantity");
                    s_price = rs.getString("selling_price");
                    row.addElement(p_id);
                    row.addElement(p_name);
                    row.addElement(stock);
                    row.addElement(s_price);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_stock.setModel(tableModel);
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }//GEN-LAST:event_formWindowOpened

    public void priceCalculation(double quantity) {
        double price = Double.parseDouble(jTextField_sell_price.getText());
        double vat = Double.parseDouble(jTextField_sell_vat.getText());
        double discount = Double.parseDouble(jTextField_sell_discount.getText());

        double total = ((price * quantity) + (vat / 100)) - (discount / 100);
        jTextField_sell_total.setText(String.valueOf(total));
    }
    
    public void dataSet(int i){
        if(i == 1){
            dataSet.put(jTextField_sell_date.getText(),jTextField_reciptNo.getText()+","+jTextField_sell_product_id.getText()+","+
                    jTextField_sell_article.getText()+","+jTextField_sell_description.getText()+","+
                    jTextField_sell_price.getText()+","+jTextField_sell_quantity.getText()+","+
                    jTextField_sell_discount.getText()+","+jTextField_sell_vat.getText()+","+jTextField_sell_total.getText());
            
            dataSetList.add(jTextField_reciptNo.getText());
        }
        /*if(i == 2){
            for(Object rn : dataSet.keySet()){
            
            Object rnNo =  rn;
            if(dataSet.containsKey(rnNo)){
                Object value = dataSet.get(rnNo);
                String values = (String) value;
                String valueSplit[],total = "";
                valueSplit = values.split(",");
                String discount = valueSplit[6];
                
                dataSet.replace(jTextField_sell_date.getText(),jTextField_reciptNo.getText()+","+jTextField_sell_product_id.getText()+","+
                    jTextField_sell_article.getText()+","+jTextField_sell_description.getText()+","+
                    jTextField_sell_price.getText()+","+jTextField_sell_quantity.getText()+","+
                    discount+","+jTextField_sell_vat.getText()+","+jTextField_sell_total.getText(),
                        jTextField_reciptNo.getText()+","+jTextField_sell_product_id.getText()+","+
                    jTextField_sell_article.getText()+","+jTextField_sell_description.getText()+","+
                    jTextField_sell_price.getText()+","+jTextField_sell_quantity.getText()+","+
                    jTextField_sell_discount.getText()+","+jTextField_sell_vat.getText()+","+jTextField_sell_total.getText());
            }
            
        }
        }*/
    }
    
    public void grossCalculation(){
        for(Object rn : dataSet.keySet()){
            
            Object rnNo =  rn;
            if(dataSet.containsKey(rnNo)){
                Object value = dataSet.get(rnNo);
                String values = (String) value;
                String valueSplit[],total = "";
                valueSplit = values.split(",");
                total = valueSplit[8];
                
                gross_total = gross_total + Double.parseDouble(total);
            }
            
        }
        jTextField_sell_gross_total.setText(String.valueOf(gross_total));
    }
    
    public void setInTable(){
        DefaultTableModel model = (DefaultTableModel) jTable_sell.getModel();
        
        for(int i = 0; i < dataSetList.size();i++){
            Vector tableline =(Vector) dataSetList.get(i);
            String rn = (String) tableline.get(0);
            model.setValueAt((Object)rn, i, 0);
        }
    }
    private void jTable_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_stockMouseClicked
        selectedProduct = jTable_stock.getValueAt(jTable_stock.getSelectedRow(), 0).toString();
        //check if seleted item double or not
        selectedProduct = jTable_stock.getValueAt(jTable_stock.getSelectedRow(), 0).toString();
        if(selectedRowList.contains(selectedProduct)){
            JOptionPane.showMessageDialog(null,"You have allready add this product.");
            return;
        }else{
            selectedRowList.add(selectedProduct);
        }
        
        
        String p_id = "", article = "", decription = "", s_price = "", quantity = "", discount = "", vat = "", unit = "";
        conn = DBConnection.connectDb();
        if (conn != null) {
            String query = "select * from stock where product_id = '" + selectedProduct + "'";
            try {
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(query);
                while (rs.next()) {
                    p_id = rs.getString("product_id");
                    article = rs.getString("article");
                    decription = rs.getString("description");
                    s_price = rs.getString("selling_price");
                    quantity = rs.getString("quantity");
                    discount = rs.getString("discount");
                    vat = rs.getString("vat");
                    unit = rs.getString("unit");
                }
                jTextField_sell_product_id.setText(p_id);
                jTextField_sell_article.setText(article);
                jTextField_sell_description.setText(decription);
                jTextField_sell_price.setText(s_price);
                jTextField_sell_quantity.setText("1");
                jTextField_sell_unit.setText(unit);
                jTextField_sell_discount.setText(discount);
                jTextField_sell_vat.setText(vat);
                priceCalculation(1);
                dataSet(1);
                grossCalculation();
                
                setInTable();
            } catch (SQLException ex) {
                Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

            }

        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }//GEN-LAST:event_jTable_stockMouseClicked

    private void jTextField_sell_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sell_quantityKeyReleased
        try {

            priceCalculation(Double.parseDouble(jTextField_sell_quantity.getText()));
        } catch (Exception e) {
            jTextField_sell_quantity.setText("");
            jTextField_sell_total.setText("");
        }

    }//GEN-LAST:event_jTextField_sell_quantityKeyReleased

    private void jTextField_sell_discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sell_discountKeyReleased
        try {
            double price = Double.parseDouble(jTextField_sell_price.getText());
            double vat = Double.parseDouble(jTextField_sell_vat.getText());
            double discount = Double.parseDouble(jTextField_sell_discount.getText());
            double quantity = Double.parseDouble(jTextField_sell_quantity.getText());
            double total = ((price * quantity) + (vat / 100)) - (discount / 100);
            jTextField_sell_total.setText(String.valueOf(total));
            
            
        } catch (Exception e) {
            jTextField_sell_discount.setText("");
            jTextField_sell_total.setText("");
        }
    }//GEN-LAST:event_jTextField_sell_discountKeyReleased

    private void jTextField_sell_vatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sell_vatKeyReleased
        try {
            double price = Double.parseDouble(jTextField_sell_price.getText());
            double vat = Double.parseDouble(jTextField_sell_vat.getText());
            double discount = Double.parseDouble(jTextField_sell_discount.getText());
            double quantity = Double.parseDouble(jTextField_sell_quantity.getText());
            double total = ((price * quantity) + (vat / 100)) - (discount / 100);
            jTextField_sell_total.setText(String.valueOf(total));
        } catch (Exception e) {
            jTextField_sell_vat.setText("");
            jTextField_sell_total.setText("");
        }
    }//GEN-LAST:event_jTextField_sell_vatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_sell_print;
    private javax.swing.JButton jButton_sell_save;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_sell;
    private javax.swing.JTable jTable_stock;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_reciptNo;
    private javax.swing.JTextField jTextField_sell_article;
    private javax.swing.JTextField jTextField_sell_date;
    private javax.swing.JTextField jTextField_sell_description;
    private javax.swing.JTextField jTextField_sell_discount;
    private javax.swing.JTextField jTextField_sell_gross_total;
    private javax.swing.JTextField jTextField_sell_price;
    private javax.swing.JTextField jTextField_sell_product_id;
    private javax.swing.JTextField jTextField_sell_quantity;
    private javax.swing.JTextField jTextField_sell_total;
    private javax.swing.JTextField jTextField_sell_unit;
    private javax.swing.JTextField jTextField_sell_vat;
    private javax.swing.JLabel minimize_label;
    // End of variables declaration//GEN-END:variables
}
