/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RABIUL
 */
public class ProductListForm extends javax.swing.JFrame {

    Connection conn = null;
    Statement statement1 = null, statement_sell = null, statement_buy = null;
    ResultSet rs = null, rs_sell = null, rs_buy = null;
    /**
     * Creates new form ProductListForm
     */
    public ProductListForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jComboBox_sell_search = new javax.swing.JComboBox<>();
        jTextField_search_product = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Products List");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Product Name"
            }
        ));
        jScrollPane1.setViewportView(jTable_productList);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 460, 460));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_sell_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Product Name" }));
        jPanel3.add(jComboBox_sell_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 150, -1));

        jTextField_search_product.setBorder(null);
        jTextField_search_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search_productKeyReleased(evt);
            }
        });
        jPanel3.add(jTextField_search_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 20));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/search.png"))); // NOI18N
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 460, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void productPopulate(int action,String cat) throws SQLException{
        conn = DBConnection.connectDb();
        if(conn != null){
            try{
                Vector columnNames = new Vector();
                Vector data = new Vector();
                int columns = 0;
                String sql = "";
                if(action == 0 && cat.equals("0")){
                    sql = "SELECT DISTINCT product_id,article FROM `products`";
                }
                else if(action == 1 && cat.equals("Product ID")){
                    String product = jTextField_search_product.getText();
                    sql = "SELECT DISTINCT product_id,article FROM `products` where product_id like '%" + product + "%'";
                }
                else if(action == 1 && cat.equals("Product Name")){
                    String product = jTextField_search_product.getText();
                    sql = "SELECT DISTINCT product_id,article FROM `products` where article like '%" + product + "%'";
                }
                String product_id = "",product_name = "";
                statement1 = conn.createStatement();
                
                columnNames.addElement("Product ID");
                columnNames.addElement("Product Name");
                
                rs = statement1.executeQuery(sql);
                while(rs.next()){
                    Vector row = new Vector(columns);
                    product_id = rs.getString("product_id");
                    product_name = rs.getString("article");
                    
                    row.addElement(product_id);
                    row.addElement(product_name);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_productList.setModel(tableModel);
            }catch(Exception e){
                e.printStackTrace();
            }finally{
                rs.close();
                statement1.close();
                conn.close();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Database Connection Failed!!!");
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
        try {
            productPopulate(0,"0");
        } catch (SQLException ex) {
            Logger.getLogger(ProductListForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField_search_productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search_productKeyReleased
        String filter = jComboBox_sell_search.getSelectedItem().toString();

        try {
            productPopulate(1, filter);
        } catch (SQLException ex) {
            Logger.getLogger(ProductListForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_search_productKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_sell_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_productList;
    private javax.swing.JTextField jTextField_search_product;
    // End of variables declaration//GEN-END:variables
}
