/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author DeeptoTV
 */
public class ReportSettingForm extends javax.swing.JFrame {

    Connection conn;
    Statement statement1, statement2;
    ResultSet rs, rs1;
    String selectedrow = "";
    String selectedCustomer = "";
    
    String path = null;
    String fileName;
    String u_type = "";

    /**
     * Creates new form ReportSettingForm
     */
    public ReportSettingForm() {
        initComponents();
    }
    public ReportSettingForm(String type) {
        u_type = type;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minimize_label = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        innerSaleFrame = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_startDate = new javax.swing.JTextField();
        jTextField_endDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_report_product = new javax.swing.JComboBox<>();
        jButton_report = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_sell_report = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField_total_profit = new javax.swing.JTextField();
        innerUserSettingFrame = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_user = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        user_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_userName = new javax.swing.JTextField();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        add_btn_user = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        delete_btn_user = new javax.swing.JButton();
        edit_btn_user = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_product = new javax.swing.JComboBox<>();
        jTextField_end_date = new javax.swing.JTextField();
        jTextField_start_date = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        innerAnalysisForm = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField_startDate_analysis = new javax.swing.JTextField();
        jTextField_endDate_analysis = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton_analysis = new javax.swing.JButton();
        jComboBox_analysis_product = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_analysis = new javax.swing.JTable();
        innerCustomerFrame = new javax.swing.JInternalFrame();
        jPanel12 = new javax.swing.JPanel();
        jComboBox_sell_search = new javax.swing.JComboBox<>();
        jTextField_search_product = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jCheckBox_discount = new javax.swing.JCheckBox();
        jButton_details = new javax.swing.JButton();
        jCheckBox_due = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_customerList = new javax.swing.JTable();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jTextField_path = new javax.swing.JTextField();
        jButton_browse = new javax.swing.JButton();
        jButton_backup = new javax.swing.JButton();
        jLabel_msg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/user_emp.png"))); // NOI18N
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 30, 20));

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rabiul");
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/cancel.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/minimize.png"))); // NOI18N
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
        });
        jPanel13.add(minimize_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/back.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setText("LogOut");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jLabel18.setBackground(new java.awt.Color(204, 0, 0));
        jLabel18.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Company Name");
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 160, 20));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/customer_report.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel8.setText("Customer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/sale_report.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(204, 0, 0));
        jLabel19.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel19.setText("Sale Report");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/user_report.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(204, 0, 0));
        jLabel20.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel20.setText("User");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/analysis_report.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(204, 0, 0));
        jLabel21.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel21.setText("Analysis");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/backup.jpg"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 0, 0));
        jLabel22.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel22.setText("BackUP");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        innerSaleFrame.setClosable(true);
        innerSaleFrame.setTitle("Sales Report");
        innerSaleFrame.setVisible(false);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Start Date");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, 20));

        jTextField_startDate.setText("yyyy/mm/dd");
        jTextField_startDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_startDateMouseClicked(evt);
            }
        });
        jPanel6.add(jTextField_startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 180, -1));

        jTextField_endDate.setText("yyyy/mm/dd");
        jTextField_endDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_endDateMouseClicked(evt);
            }
        });
        jPanel6.add(jTextField_endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 180, -1));

        jLabel10.setBackground(new java.awt.Color(204, 0, 0));
        jLabel10.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("End Date");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 100, 20));

        jComboBox_report_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product.." }));
        jPanel6.add(jComboBox_report_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 150, -1));

        jButton_report.setText("Report Generate");
        jButton_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reportActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 220, 40));

        jLabel11.setBackground(new java.awt.Color(204, 0, 0));
        jLabel11.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Product");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 20));

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_sell_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL", "Product ID", "Product Name", "IN Stock", "Selling quantity", "Buying Price", "Selling Price", "Cost", "Sell (TK)", "Profit/Loss"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_sell_report);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 400));

        jLabel9.setBackground(new java.awt.Color(204, 0, 0));
        jLabel9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 100, 20));

        jTextField_total_profit.setEditable(false);
        jTextField_total_profit.setText("0");
        jPanel7.add(jTextField_total_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 150, 60));

        javax.swing.GroupLayout innerSaleFrameLayout = new javax.swing.GroupLayout(innerSaleFrame.getContentPane());
        innerSaleFrame.getContentPane().setLayout(innerSaleFrameLayout);
        innerSaleFrameLayout.setHorizontalGroup(
            innerSaleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        innerSaleFrameLayout.setVerticalGroup(
            innerSaleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerSaleFrameLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(innerSaleFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1070, 560));

        innerUserSettingFrame.setClosable(true);
        innerUserSettingFrame.setTitle("USer Customize");
        innerUserSettingFrame.setVisible(false);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_userMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_user);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 370));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 480, 390));

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee" }));
        jPanel10.add(user_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 200, -1));

        jLabel6.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADD New USER");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, -1));

        jLabel12.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("User Name");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        jTextField_userName.setBorder(null);
        jTextField_userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_userNameFocusGained(evt);
            }
        });
        jPanel10.add(jTextField_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, 20));

        jPasswordField_pass.setBorder(null);
        jPasswordField_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passFocusGained(evt);
            }
        });
        jPanel10.add(jPasswordField_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 200, 20));

        jLabel4.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, -1));

        jLabel13.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("User Type");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, -1));

        add_btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/add_btn.png"))); // NOI18N
        add_btn_user.setText("Add");
        add_btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btn_userActionPerformed(evt);
            }
        });
        jPanel10.add(add_btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 260));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/delete_btn.png"))); // NOI18N
        delete_btn_user.setText("Delete");
        delete_btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btn_userActionPerformed(evt);
            }
        });
        jPanel11.add(delete_btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        edit_btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/edit_btn.jpg"))); // NOI18N
        edit_btn_user.setText("Update");
        edit_btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btn_userActionPerformed(evt);
            }
        });
        jPanel11.add(edit_btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 400, 110));

        javax.swing.GroupLayout innerUserSettingFrameLayout = new javax.swing.GroupLayout(innerUserSettingFrame.getContentPane());
        innerUserSettingFrame.getContentPane().setLayout(innerUserSettingFrameLayout);
        innerUserSettingFrameLayout.setHorizontalGroup(
            innerUserSettingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerUserSettingFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        innerUserSettingFrameLayout.setVerticalGroup(
            innerUserSettingFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerUserSettingFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(innerUserSettingFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 970, 490));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(false);

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("End Date");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        jLabel15.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sale Analysis");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, -1));

        jLabel16.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Start date");
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        jComboBox_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Egg" }));
        jPanel14.add(jComboBox_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));
        jPanel14.add(jTextField_end_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, -1));
        jPanel14.add(jTextField_start_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));

        jLabel17.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Product");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Show Analysis");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 160, 60));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jPanel2.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1090, 550));

        innerAnalysisForm.setClosable(true);
        innerAnalysisForm.setTitle("Product Analysis");
        innerAnalysisForm.setVisible(false);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(51, 0, 102));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Start Date");
        jPanel21.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField_startDate_analysis.setText("yyyy-mm-dd");
        jPanel21.add(jTextField_startDate_analysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        jTextField_endDate_analysis.setText("yyyy-mm-dd");
        jPanel21.add(jTextField_endDate_analysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("End Date");
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jButton_analysis.setBackground(new java.awt.Color(255, 255, 255));
        jButton_analysis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_analysis.setText("Analysis");
        jButton_analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_analysisActionPerformed(evt);
            }
        });
        jPanel21.add(jButton_analysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jPanel5.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 80));

        jComboBox_analysis_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product.." }));
        jComboBox_analysis_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_analysis_productActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox_analysis_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 150, -1));

        jLabel53.setBackground(new java.awt.Color(204, 0, 0));
        jLabel53.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Product");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 100, 20));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 960, 100));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_analysis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable_analysis);

        jPanel22.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 360));

        jPanel4.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 960, 360));

        javax.swing.GroupLayout innerAnalysisFormLayout = new javax.swing.GroupLayout(innerAnalysisForm.getContentPane());
        innerAnalysisForm.getContentPane().setLayout(innerAnalysisFormLayout);
        innerAnalysisFormLayout.setHorizontalGroup(
            innerAnalysisFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        innerAnalysisFormLayout.setVerticalGroup(
            innerAnalysisFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(innerAnalysisForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 1030, 520));

        innerCustomerFrame.setBackground(new java.awt.Color(0, 102, 102));
        innerCustomerFrame.setClosable(true);
        innerCustomerFrame.setTitle("Customer Details");
        innerCustomerFrame.setVisible(false);

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_sell_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Phone NO", "Address" }));
        jPanel12.add(jComboBox_sell_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 150, -1));

        jTextField_search_product.setBorder(null);
        jTextField_search_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search_productKeyReleased(evt);
            }
        });
        jPanel12.add(jTextField_search_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, 20));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/search.png"))); // NOI18N
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jCheckBox_discount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_discount.setText("Discount");
        jCheckBox_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_discountActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBox_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jButton_details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_details.setText("View Details");
        jButton_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_detailsActionPerformed(evt);
            }
        });
        jPanel12.add(jButton_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jCheckBox_due.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_due.setText("Due");
        jCheckBox_due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_dueActionPerformed(evt);
            }
        });
        jPanel12.add(jCheckBox_due, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_customerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_customerListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_customerList);

        jPanel20.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout innerCustomerFrameLayout = new javax.swing.GroupLayout(innerCustomerFrame.getContentPane());
        innerCustomerFrame.getContentPane().setLayout(innerCustomerFrameLayout);
        innerCustomerFrameLayout.setHorizontalGroup(
            innerCustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCustomerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerCustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
                .addContainerGap())
        );
        innerCustomerFrameLayout.setVerticalGroup(
            innerCustomerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerCustomerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(innerCustomerFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1040, 550));

        jInternalFrame2.setVisible(false);

        jPanel23.setBackground(new java.awt.Color(0, 102, 102));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(0, 102, 102));
        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(jTextField_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, -1));

        jButton_browse.setText("Brrowse Path");
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browseActionPerformed(evt);
            }
        });
        jPanel24.add(jButton_browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jButton_backup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_backup.setText("Backup Now");
        jButton_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backupActionPerformed(evt);
            }
        });
        jPanel24.add(jButton_backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel_msg.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_msg.setText("jLabel26");
        jPanel24.add(jLabel_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 480, -1));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 530, 270));

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 660, 370));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/report1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        dispose();
        LoginForm lf = new LoginForm();
        lf.setLocation(100, 50);
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        dispose();
        //LoginForm lf = new LoginForm();
        HomeForm lf = new HomeForm(u_type);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginForm lf = new LoginForm();
        lf.setLocation(100, 50);
        lf.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reportActionPerformed
        Vector columnNames = new Vector();
        Vector data = new Vector();

        int columns = 0;
        String product = jComboBox_report_product.getSelectedItem().toString();
        String start_date = jTextField_startDate.getText();
        String end_date = jTextField_endDate.getText();
        int slNo = 0;
        String product_id = "", article = "", stock = "", s_quantity = "";
        double b_price = 0, s_price = 0, cost = 0, sell = 0, profit = 0;
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                String query = "";
                if (product.equals("Select Product..")) {
                    query = "select product_id,article,price as s_price,sum(quantity) as quantity,sum(total) as price  from sell where date(date) >= '" + start_date + "' and date(date) <= '" + end_date + "'  group by product_id,article,price";

                } else {
                    query = "select product_id,article,price as s_price,sum(quantity) as quantity,sum(total) as price  from sell where date(date) >= '" + start_date + "' and date(date) <= '" + end_date + "' and article ='" + product + "' group by product_id,article,price";

                }

                statement1 = conn.createStatement();
                rs = statement1.executeQuery(query);

                columnNames.addElement("SL");
                columnNames.addElement("Product ID");
                columnNames.addElement("Product Name");
                columnNames.addElement("Stock");
                columnNames.addElement("buying Price");
                columnNames.addElement("Selling quantity");
                columnNames.addElement("S_Price");
                columnNames.addElement("Cost");
                columnNames.addElement("Sale");
                columnNames.addElement("Total");
                int sl = 0;
                double totalProfit = 0;
                while (rs.next()) {
                    Vector row = new Vector(columns);
                    product_id = rs.getString("product_id");
                    article = rs.getString("article");
                    s_price = rs.getDouble("s_price");
                    s_quantity = rs.getString("quantity");
                    sell = rs.getDouble("price");
                    sl = sl + 1;
                    String stockIN = "", bPrice = "";
                    String stockQuery = "select * from stock where product_id = '" + product_id + "'";
                    statement2 = conn.createStatement();
                    rs1 = statement2.executeQuery(stockQuery);
                    while (rs1.next()) {
                        stockIN = rs1.getString("quantity");
                        bPrice = rs1.getString("buying_price");
                    }
                    rs1.close();
                    statement2.close();
                    cost = Double.parseDouble(s_quantity) * Double.parseDouble(bPrice);
                    profit = sell - cost;
                    totalProfit = totalProfit + profit;
                    row.addElement(sl);
                    row.addElement(product_id);
                    row.addElement(article);
                    row.addElement(stockIN);
                    row.addElement(bPrice);
                    row.addElement(s_quantity);
                    row.addElement(s_price);
                    row.addElement(cost);
                    row.addElement(sell);
                    row.addElement(profit);
                    //row.addElement(t_type);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_sell_report.setModel(tableModel);
                jTextField_total_profit.setText(String.valueOf(totalProfit));
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database connection Failed!!!");
        }
    }//GEN-LAST:event_jButton_reportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        edit_btn_user.setEnabled(false);
        delete_btn_user.setEnabled(false);
        innerUserSettingFrame.setVisible(false);
        innerSaleFrame.setVisible(false);
        innerCustomerFrame.setVisible(true);

        try {
            CustomerPopulate(0, "0");
        } catch (SQLException ex) {
            Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userNameFocusGained

    }//GEN-LAST:event_jTextField_userNameFocusGained

    private void jPasswordField_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passFocusGained

    }//GEN-LAST:event_jPasswordField_passFocusGained

    private void delete_btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn_userActionPerformed
        // TODO add your handling code here:
        selectedrow = jTable_user.getValueAt(jTable_user.getSelectedRow(), 0).toString();
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                statement1 = conn.createStatement();
                String sql_delete = "delete from users where id = '" + selectedrow + "'";

                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to Delete this product?", "Warning", dialogButton);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    statement1.executeUpdate(sql_delete);
                    JOptionPane.showMessageDialog(null, "user Deleted!!!");
                    userPopulate();
                    jTextField_userName.setText("");
                    add_btn_user.setEnabled(true);
                    edit_btn_user.setEnabled(false);
                    delete_btn_user.setEnabled(false);

                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "DataBase Connection Failed");
        }
    }//GEN-LAST:event_delete_btn_userActionPerformed

    private void edit_btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btn_userActionPerformed
        selectedrow = jTable_user.getValueAt(jTable_user.getSelectedRow(), 0).toString();
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                String user = "", type = "";
                statement1 = conn.createStatement();
                String sql = "select * from users where id = '" + selectedrow + "'";

                rs = statement1.executeQuery(sql);
                while (rs.next()) {
                    type = rs.getString("user_type");
                    user = rs.getString("user_name");
                }
                UserUpdateForm update = new UserUpdateForm(user, type, conn, selectedrow);

                update.setDefaultCloseOperation(update.EXIT_ON_CLOSE);
                update.setLocation(100, 100);
                update.setVisible(true);

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "DataBase Connection Failed");
        }


    }//GEN-LAST:event_edit_btn_userActionPerformed

    private void add_btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btn_userActionPerformed
        // TODO add your handling code here:
        String u_type = user_type.getSelectedItem().toString();
        String u_name = jTextField_userName.getText();
        String pass = jPasswordField_pass.getText();
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                int count = 0;
                statement1 = conn.createStatement();
                String sql = "select count(id) from users where user_type = '" + u_type + "' and user_name = '" + u_name + "'";
                rs = statement1.executeQuery(sql);
                while (rs.next()) {
                    count = rs.getInt(1);
                }
                rs.close();
                statement1.close();

                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Already have a user.Please try another !!!");
                } else {
                    EncryptData encrypt = new EncryptData();
                    char[] pwd = jPasswordField_pass.getPassword();
                    String password = encrypt.encryptPass(String.copyValueOf(pwd));

                    if (u_name.equals("") || pass.equals("")) {
                        JOptionPane.showMessageDialog(null, "Please Fill up all fields ...");
                    }
                    SqlManager sqlManager = new SqlManager();
                    sqlManager.userInfoInsert_setting(u_name, password, u_type);
                    userPopulate();
                    jTextField_userName.setText("");
                    jPasswordField_pass.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed !!!");
        }


    }//GEN-LAST:event_add_btn_userActionPerformed

    public void userPopulate() throws SQLException {
        String u_name = "", u_type = "", password = "", id = "";
        Vector columnNames = new Vector();
        Vector data = new Vector();
        int columns = 0;
        String sql = "select * from users";
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(sql);
                //this.jTable1.setModel(DbUtils.resultSetToTableModel(rs_razuna));
                columnNames.addElement("ID");
                columnNames.addElement("User Type");
                columnNames.addElement("User Name");
                //columnNames.addElement("Password");
                // columnNames.addElement("Trans. Type");

                while (rs.next()) {
                    Vector row = new Vector(columns);
                    id = rs.getString("id");
                    u_type = rs.getString("user_type");
                    u_name = rs.getString("user_name");
                    //password = rs.getString("password");

                    row.addElement(id);
                    row.addElement(u_type);
                    row.addElement(u_name);
                    //row.addElement(password);
                    //row.addElement(t_type);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_user.setModel(tableModel);

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                rs.close();
                statement1.close();
                conn.close();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }
    private void jTable_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_userMouseClicked
        // TODO add your handling code here:
        add_btn_user.setEnabled(false);
        edit_btn_user.setEnabled(true);
        delete_btn_user.setEnabled(true);
        String selectedUser = jTable_user.getValueAt(jTable_user.getSelectedRow(), 0).toString();
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                String sql = "select * from users where id = '" + selectedUser + "'";
                String type = "", user = "";
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(sql);
                while (rs.next()) {
                    type = rs.getString("user_type");
                    user = rs.getString("user_name");
                }
                user_type.setSelectedItem(type);
                jTextField_userName.setText(user);
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed !!!");
        }
    }//GEN-LAST:event_jTable_userMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        conn = DBConnection.connectDb();
        String product = jComboBox_product.getSelectedItem().toString();
        String s_date = jTextField_start_date.getText();
        String e_date = jTextField_end_date.getText();
        if (conn != null) {
            try {

            } catch (Exception e) {

            } finally {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        edit_btn_user.setEnabled(false);
        delete_btn_user.setEnabled(false);
        innerUserSettingFrame.setVisible(false);
        innerSaleFrame.setVisible(true);
        innerCustomerFrame.setVisible(false);
        conn = DBConnection.connectDb();

        if (conn != null) {
            try {
                String sql = "select article from stock";
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(sql);
                while (rs.next()) {
                    jComboBox_report_product.addItem(rs.getString("article"));
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        innerSaleFrame.setVisible(false);
        innerUserSettingFrame.setVisible(true);
        innerCustomerFrame.setVisible(false);
        try {
            userPopulate();
        } catch (SQLException ex) {
            Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        innerUserSettingFrame.setVisible(false);
        innerSaleFrame.setVisible(false);
        innerCustomerFrame.setVisible(false);
        innerAnalysisForm.setVisible(true);
        conn = DBConnection.connectDb();

        if (conn != null) {
            try {
                String sql = "select article from stock";
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(sql);
                while (rs.next()) {
                    jComboBox_analysis_product.addItem(rs.getString("article"));
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField_startDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_startDateMouseClicked
        // TODO add your handling code here:
        jTextField_startDate.setText("");
    }//GEN-LAST:event_jTextField_startDateMouseClicked

    private void jTextField_endDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_endDateMouseClicked
        // TODO add your handling code here:
        jTextField_endDate.setText("");
    }//GEN-LAST:event_jTextField_endDateMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    public void CustomerPopulate(int action, String cat) throws SQLException {
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                Vector columnNames = new Vector();
                Vector data = new Vector();
                int columns = 0;
                String sql = "";
                if (action == 0 && cat.equals("0")) {
                    sql = "SELECT * FROM `customer_details`";
                } else if (action == 1 && cat.equals("Name")) {
                    String product = jTextField_search_product.getText();
                    sql = "SELECT * FROM `customer_details` where cus_name like '%" + product + "%'";
                } else if (action == 1 && cat.equals("Phone NO")) {
                    String product = jTextField_search_product.getText();
                    sql = "SELECT * FROM `customer_details` where cus_phone like '%" + product + "%'";
                } else if (action == 1 && cat.equals("Address")) {
                    String product = jTextField_search_product.getText();
                    sql = "SELECT * FROM `customer_details` where address like '%" + product + "%'";
                } else if (action == 3 && cat.equals("0")) {
                    String product = jTextField_search_product.getText();
                    sql = "SELECT * FROM `customer_details` where discount > 0";
                } else if (action == 2 && cat.equals("0")) {
                    String product = jTextField_search_product.getText();
                    sql = "SELECT * FROM `customer_details` where change_due > 0";
                }
                String recipt_no = "", cus_name = "", cus_phone = "", address = "", total = "", payment = "", discount = "", change = "", date = "";
                statement1 = conn.createStatement();

                columnNames.addElement("Recipt No");
                columnNames.addElement("Customer Name");
                columnNames.addElement("Phone No");
                columnNames.addElement("Address");
                columnNames.addElement("Total");
                columnNames.addElement("Payment");
                columnNames.addElement("Discount");
                columnNames.addElement("Change");
                columnNames.addElement("Date");

                rs = statement1.executeQuery(sql);
                while (rs.next()) {
                    Vector row = new Vector(columns);
                    recipt_no = rs.getString("recipt_no");
                    cus_name = rs.getString("cus_name");
                    cus_phone = rs.getString("cus_phone");
                    address = rs.getString("address");
                    total = rs.getString("total");
                    payment = rs.getString("payment");
                    discount = rs.getString("discount");
                    change = rs.getString("change_due");
                    date = rs.getString("date");

                    row.addElement(recipt_no);
                    row.addElement(cus_name);
                    row.addElement(cus_phone);
                    row.addElement(address);
                    row.addElement(total);
                    row.addElement(payment);
                    row.addElement(discount);
                    row.addElement(change);
                    row.addElement(date);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_customerList.setModel(tableModel);
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                rs.close();
                statement1.close();
                conn.close();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }
    private void jTextField_search_productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search_productKeyReleased
        String filter = jComboBox_sell_search.getSelectedItem().toString();

        try {
            CustomerPopulate(1, filter);
        } catch (SQLException ex) {
            Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_search_productKeyReleased

    private void jCheckBox_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_discountActionPerformed

        if (jCheckBox_discount.isSelected()) {
            try {
                // TODO add your handling code here:
                CustomerPopulate(3, "0");
            } catch (SQLException ex) {
                Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                CustomerPopulate(0, "0");
            } catch (SQLException ex) {
                Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCheckBox_discountActionPerformed

    private void jCheckBox_dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_dueActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_due.isSelected()) {
            try {
                // TODO add your handling code here:
                CustomerPopulate(2, "0");
            } catch (SQLException ex) {
                Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                CustomerPopulate(0, "0");
            } catch (SQLException ex) {
                Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCheckBox_dueActionPerformed

    private void jTable_customerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_customerListMouseClicked
        // TODO add your handling code here:
        selectedCustomer = jTable_customerList.getValueAt(jTable_customerList.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable_customerListMouseClicked

    private void jButton_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_detailsActionPerformed
        // TODO add your handling code here:
        SellDetailsForm sdf = new SellDetailsForm(selectedCustomer);
        
        sdf.setDefaultCloseOperation(sdf.DISPOSE_ON_CLOSE);
        sdf.setLocation(20, 100);
       
        sdf.setVisible(true);
    }//GEN-LAST:event_jButton_detailsActionPerformed

    public void analysisPopulate(){
        Vector columnNames = new Vector();
        Vector data = new Vector();

        int columns = 0;
        String product = jComboBox_analysis_product.getSelectedItem().toString();
        String start_date = jTextField_startDate_analysis.getText();
        String end_date = jTextField_endDate_analysis.getText();
        int slNo = 0;
        String product_id = "", article = "", stock = "", s_quantity = "";
        double b_price = 0, s_price = 0, cost = 0, sell = 0, profit = 0;
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                String query = "";
                if (product.equals("Select Product..")) {
                    query = "select product_id,article,selling_price as s_price,sum(quantity) as quantity from products where date(date) >= '" + start_date + "' and date(date) <= '" + end_date + "'  group by product_id,article,selling_price";

                } else {
                    query = "select product_id,article,selling_price as s_price,sum(quantity) as quantity  from products where date(date) >= '" + start_date + "' and date(date) <= '" + end_date + "' and article ='" + product + "' group by product_id,article,selling_price";

                }

                statement1 = conn.createStatement();
                rs = statement1.executeQuery(query);

                columnNames.addElement("SL");
                columnNames.addElement("Product ID");
                columnNames.addElement("Product Name");
                columnNames.addElement("Stock");
                columnNames.addElement("Total Buy");
                columnNames.addElement("Total Sell");
                int sl = 0;
                double totalProfit = 0;
                while (rs.next()) {
                    Vector row = new Vector(columns);
                    product_id = rs.getString("product_id");
                    article = rs.getString("article");
                    s_quantity = rs.getString("quantity");
                    
                    sl = sl + 1;
                    String stockIN = "", bPrice = "";
                    String stockQuery = "select * from stock where product_id = '" + product_id + "'";
                    statement2 = conn.createStatement();
                    rs1 = statement2.executeQuery(stockQuery);
                    while (rs1.next()) {
                        stockIN = rs1.getString("quantity");
                    }
                    rs1.close();
                    statement2.close();
                    
                    String total_buy = "";
                    String buyQuery = "select sum(quantity) as quantity from sell where product_id = '" + product_id + "' and date(date) >= '" + start_date + "' and date(date) <= '" + end_date + "'  group by product_id";
                    statement2 = conn.createStatement();
                    rs1 = statement2.executeQuery(buyQuery);
                    while (rs1.next()) {
                        total_buy = rs1.getString("quantity");
                    }
                    rs1.close();
                    statement2.close();
                    
                    
                    row.addElement(sl);
                    row.addElement(product_id);
                    row.addElement(article);
                    row.addElement(stockIN);
                    row.addElement(s_quantity);
                    row.addElement(total_buy);
                    //row.addElement(t_type);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_analysis.setModel(tableModel);
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(ReportSettingForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database connection Failed!!!");
        }
    }
    private void jButton_analysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_analysisActionPerformed
        // TODO add your handling code here:
        analysisPopulate();
    }//GEN-LAST:event_jButton_analysisActionPerformed

    private void jComboBox_analysis_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_analysis_productActionPerformed
        // TODO add your handling code here:
        analysisPopulate();
    }//GEN-LAST:event_jComboBox_analysis_productActionPerformed

    private void jButton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browseActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        String date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        
        try{
            File f = fc.getSelectedFile();
            path = f.getAbsolutePath();
            path = path.replace("\\", "/");
            path = path + "_"+date+".sql";
            jTextField_path.setText(path);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_browseActionPerformed

    private void jButton_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backupActionPerformed
        // TODO add your handling code here:
        Process p = null;
        try{
            Runtime runtime = Runtime.getRuntime();
            p = runtime.exec("C:/xampp/mysql/bin/mysqldump.exe -uroot --add-drop-database -B pos_system -r"+path);
            
            int processComplete = p.waitFor();
            if(processComplete == 0){
                jLabel_msg.setText("BackUp created in "+jTextField_path.getText());
            }
            else{
                jLabel_msg.setText("BackUp Not created");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_backupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportSettingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn_user;
    private javax.swing.JButton delete_btn_user;
    private javax.swing.JButton edit_btn_user;
    private javax.swing.JInternalFrame innerAnalysisForm;
    private javax.swing.JInternalFrame innerCustomerFrame;
    private javax.swing.JInternalFrame innerSaleFrame;
    private javax.swing.JInternalFrame innerUserSettingFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_analysis;
    private javax.swing.JButton jButton_backup;
    private javax.swing.JButton jButton_browse;
    private javax.swing.JButton jButton_details;
    private javax.swing.JButton jButton_report;
    private javax.swing.JCheckBox jCheckBox_discount;
    private javax.swing.JCheckBox jCheckBox_due;
    private javax.swing.JComboBox<String> jComboBox_analysis_product;
    private javax.swing.JComboBox<String> jComboBox_product;
    private javax.swing.JComboBox<String> jComboBox_report_product;
    private javax.swing.JComboBox<String> jComboBox_sell_search;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_msg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField_pass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_analysis;
    private javax.swing.JTable jTable_customerList;
    private javax.swing.JTable jTable_sell_report;
    private javax.swing.JTable jTable_user;
    private javax.swing.JTextField jTextField_endDate;
    private javax.swing.JTextField jTextField_endDate_analysis;
    private javax.swing.JTextField jTextField_end_date;
    private javax.swing.JTextField jTextField_path;
    private javax.swing.JTextField jTextField_search_product;
    private javax.swing.JTextField jTextField_startDate;
    private javax.swing.JTextField jTextField_startDate_analysis;
    private javax.swing.JTextField jTextField_start_date;
    private javax.swing.JTextField jTextField_total_profit;
    private javax.swing.JTextField jTextField_userName;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JComboBox<String> user_type;
    // End of variables declaration//GEN-END:variables
}
