/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RABIUL
 */
public class SellDetailsForm extends javax.swing.JFrame {

    Connection conn = null;
    Statement statement1 = null,statement_cus = null;
    ResultSet rs = null,rs_cus = null;
    String rn_no = "";
    /**
     * Creates new form SellDetailsForm
     */
    public SellDetailsForm() {
        initComponents();
    }

    public SellDetailsForm(String rn) {
        rn_no = rn;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_sale = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jTextField_cus_phone = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField_cus_name = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_cus_address = new javax.swing.JTextArea();
        jTextField_cus_date = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_sell_gross_total = new javax.swing.JTextField();
        jTextField_sell_payment = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_sell_change = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_sell_discount_tk = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Your Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Recipt #", "Product ID", "Article", "Desc", "Unit Price", "Quantity", "Discount ", "VAT%", "Total", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_sale);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 870, 330));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 870, 370));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_cus_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cus_phoneActionPerformed(evt);
            }
        });
        jTextField_cus_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_cus_phoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_cus_phoneKeyReleased(evt);
            }
        });
        jPanel11.add(jTextField_cus_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, -1));

        jLabel35.setBackground(new java.awt.Color(204, 0, 0));
        jLabel35.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Due Customer Details");
        jPanel11.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jLabel36.setBackground(new java.awt.Color(204, 0, 0));
        jLabel36.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Phone No");
        jPanel11.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel39.setBackground(new java.awt.Color(204, 0, 0));
        jLabel39.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Customer Name");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jTextField_cus_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_cus_nameKeyReleased(evt);
            }
        });
        jPanel11.add(jTextField_cus_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));

        jLabel43.setBackground(new java.awt.Color(204, 0, 0));
        jLabel43.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Address");
        jPanel11.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jTextArea_cus_address.setColumns(20);
        jTextArea_cus_address.setRows(5);
        jScrollPane3.setViewportView(jTextArea_cus_address);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, 70));

        jTextField_cus_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_cus_dateKeyReleased(evt);
            }
        });
        jPanel11.add(jTextField_cus_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, -1));

        jLabel40.setBackground(new java.awt.Color(204, 0, 0));
        jLabel40.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Date");
        jPanel11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 300, 210));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jTextField_sell_gross_total.setText("0");
        jPanel7.add(jTextField_sell_gross_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 30));

        jTextField_sell_payment.setText("0");
        jTextField_sell_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sell_paymentKeyReleased(evt);
            }
        });
        jPanel7.add(jTextField_sell_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, 30));

        jLabel17.setBackground(new java.awt.Color(204, 0, 0));
        jLabel17.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Payment");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        jTextField_sell_change.setEditable(false);
        jTextField_sell_change.setText("0");
        jPanel7.add(jTextField_sell_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, 30));

        jLabel18.setBackground(new java.awt.Color(204, 0, 0));
        jLabel18.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Change/Due");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));

        jLabel19.setBackground(new java.awt.Color(204, 0, 0));
        jLabel19.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TK");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 40, 20));

        jTextField_sell_discount_tk.setText("0");
        jTextField_sell_discount_tk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sell_discount_tkKeyReleased(evt);
            }
        });
        jPanel7.add(jTextField_sell_discount_tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 30));

        jLabel33.setBackground(new java.awt.Color(204, 0, 0));
        jLabel33.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Discount");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 300, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String rnNo = "", p_id = "", p_name = "", desc = "", s_price = "", quantity = "", discount = "", vat = "", total = "", date = "", t_type = "";
        Vector columnNames = new Vector();
        Vector data = new Vector();
        int columns = 0;
        String sql = "select * from sell where recipt_no = '" + rn_no + "'";
        conn = DBConnection.connectDb();
        if (conn != null) {
            try {
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(sql);
                //this.jTable1.setModel(DbUtils.resultSetToTableModel(rs_razuna));

                columnNames.addElement("Recipt #");
                columnNames.addElement("Product ID");
                columnNames.addElement("article");
                columnNames.addElement("Desc");
                columnNames.addElement("Unit Price");
                columnNames.addElement("Quantity");
                columnNames.addElement("Discount%");
                columnNames.addElement("VAT%");
                columnNames.addElement("Total");
                columnNames.addElement("Date");
                // columnNames.addElement("Trans. Type");

                while (rs.next()) {
                    Vector row = new Vector(columns);
                    rnNo = rs.getString("recipt_no");
                    p_id = rs.getString("product_id");
                    p_name = rs.getString("article");
                    desc = rs.getString("description");
                    s_price = rs.getString("price");
                    quantity = rs.getString("quantity");
                    discount = rs.getString("discount");
                    vat = rs.getString("vat");
                    total = rs.getString("total");
                    date = rs.getString("date");
                    //t_type = rs.getString("quantity");

                    row.addElement(rnNo);
                    row.addElement(p_id);
                    row.addElement(p_name);
                    row.addElement(desc);
                    row.addElement(s_price);
                    row.addElement(quantity);
                    row.addElement(discount);
                    row.addElement(vat);
                    row.addElement(total);
                    row.addElement(date);
                    //row.addElement(t_type);
                    data.addElement(row);
                }
                DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
                jTable_sale.setModel(tableModel);
                
                //add customer details
                String cus_name = "",cus_phone = "", cus_address = "",total_c = "",paid ="",change = "",discount_c = "",date_c = "";
                String sql_cus = "select * from customer_details where recipt_no = '"+rn_no+"'";
                
                statement_cus = conn.createStatement();
                rs_cus = statement_cus.executeQuery(sql_cus);
                
                while(rs_cus.next()){
                    cus_name = rs_cus.getString("cus_name");
                    cus_phone = rs_cus.getString("cus_phone");
                    cus_address = rs_cus.getString("address");
                    total_c = rs_cus.getString("total");
                    paid = rs_cus.getString("payment");
                    change = rs_cus.getString("change_due");
                    discount_c = rs_cus.getString("discount");
                    date_c = rs_cus.getString("date");
                }
                rs_cus.close();
                statement_cus.close();
                
                jTextField_cus_date.setText(date_c);
                jTextField_cus_name.setText(cus_name);
                jTextField_cus_phone.setText(cus_phone);
                jTextArea_cus_address.setText(cus_address);
                jTextField_sell_gross_total.setText(total_c);
                jTextField_sell_payment.setText(paid);
                jTextField_sell_change.setText(change);
                jTextField_sell_discount_tk.setText(discount_c);
                
                
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    rs.close();
                    statement1.close();
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(PointOfSaleForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Database Connection Failed!!!");
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField_cus_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cus_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cus_phoneActionPerformed

    private void jTextField_cus_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cus_phoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cus_phoneKeyPressed

    private void jTextField_cus_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cus_phoneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cus_phoneKeyReleased

    private void jTextField_cus_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cus_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cus_nameKeyReleased

    private void jTextField_sell_paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sell_paymentKeyReleased
        try {
            double total = Double.parseDouble(jTextField_sell_gross_total.getText());
            double pay = Double.parseDouble(jTextField_sell_payment.getText());
            jTextField_sell_change.setText(String.valueOf(total - pay));
        } catch (Exception e) {
            jTextField_sell_payment.setText("");
        }
    }//GEN-LAST:event_jTextField_sell_paymentKeyReleased

    private void jTextField_sell_discount_tkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sell_discount_tkKeyReleased
        // TODO add your handling code here:
        try {
            double dis = Double.parseDouble(jTextField_sell_discount_tk.getText());
            double total = Double.parseDouble(jTextField_sell_gross_total.getText());
            double paid = Double.parseDouble(jTextField_sell_payment.getText());
            jTextField_sell_change.setText(String.valueOf(total - (paid + dis)));
        } catch (Exception e) {
            jTextField_sell_discount_tk.setText("");
        }
    }//GEN-LAST:event_jTextField_sell_discount_tkKeyReleased

    private void jTextField_cus_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cus_dateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cus_dateKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_sale;
    private javax.swing.JTextArea jTextArea_cus_address;
    private javax.swing.JTextField jTextField_cus_date;
    private javax.swing.JTextField jTextField_cus_name;
    private javax.swing.JTextField jTextField_cus_phone;
    private javax.swing.JTextField jTextField_sell_change;
    private javax.swing.JTextField jTextField_sell_discount_tk;
    private javax.swing.JTextField jTextField_sell_gross_total;
    private javax.swing.JTextField jTextField_sell_payment;
    // End of variables declaration//GEN-END:variables
}
