/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uidesign;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RABIUL
 */
public class UserUpdateForm extends javax.swing.JFrame {
    Connection conn;
    Statement statement1, statement2;
    ResultSet rs, rs1;
    String user_a = "",type_a = "",id = "";
    /**
     * Creates new form UserUpdateForm
     */
    public UserUpdateForm() {
        initComponents();
    }
    public UserUpdateForm(String user,String type,Connection conna,String select) {
        user_a = user;
        type_a = type;
        conn = conna;
        id = select;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_userName_up = new javax.swing.JTextField();
        jPasswordField_pass_new = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField_pass_up = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        user_type_up = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Update User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));

        jTextField_userName_up.setText("Enter User Name");
        jTextField_userName_up.setBorder(null);
        jTextField_userName_up.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_userName_upFocusGained(evt);
            }
        });
        jPanel3.add(jTextField_userName_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 20));

        jPasswordField_pass_new.setText("jPasswordField1");
        jPasswordField_pass_new.setBorder(null);
        jPasswordField_pass_new.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pass_newFocusGained(evt);
            }
        });
        jPasswordField_pass_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_pass_newMouseClicked(evt);
            }
        });
        jPasswordField_pass_new.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_pass_newKeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordField_pass_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 20));

        jLabel4.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, -1));

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setText("       Sign Up");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 110, 30));

        jPasswordField_pass_up.setText("jPasswordField1");
        jPasswordField_pass_up.setBorder(null);
        jPasswordField_pass_up.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pass_upFocusGained(evt);
            }
        });
        jPasswordField_pass_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_pass_upMouseClicked(evt);
            }
        });
        jPasswordField_pass_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_pass_upKeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordField_pass_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 20));

        jLabel5.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Old Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        user_type_up.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee" }));
        user_type_up.setBorder(null);
        jPanel3.add(user_type_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, -1));

        jLabel13.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("User Type");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 240));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uidesign/images/cancel.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_userName_upFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_userName_upFocusGained
        // TODO add your handling code here:
        jTextField_userName_up.setText("");
    }//GEN-LAST:event_jTextField_userName_upFocusGained

    private void jPasswordField_pass_newFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pass_newFocusGained
        // TODO add your handling code here:
        jPasswordField_pass_new.setText("");
    }//GEN-LAST:event_jPasswordField_pass_newFocusGained

    private void jPasswordField_pass_newKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pass_newKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pass_newKeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        EncryptData encrypt = new EncryptData();
        String old_pass = "",new_pass = "",type = "",userName ="",pass = "";
        type = user_type_up.getSelectedItem().toString();
        userName = jTextField_userName_up.getText();
        char[] pwd_old = jPasswordField_pass_up.getPassword();
        char[] pwd_new = jPasswordField_pass_new.getPassword();
        
        old_pass = encrypt.encryptPass(String.copyValueOf(pwd_old));
        new_pass = encrypt.encryptPass(String.copyValueOf(pwd_new));
        conn = DBConnection.connectDb();
        if(conn != null){
            String old_pass_query = "select password from users where id = '"+id+"'";
            try {
                statement1 = conn.createStatement();
                rs = statement1.executeQuery(old_pass_query);
                while(rs.next()){
                    pass = rs.getString("password");
                }
                rs.close();
                statement1.close();
                if(!pass.equals(old_pass)){
                    JOptionPane.showMessageDialog(null, "Please enter correct old password");
                    return;
                }else{
                    String update = "update users set user_type = '"+type+"',user_name = '"+userName+"',password = '"+new_pass+"' where id = '"+id+"'";
                    statement1 = conn.createStatement();
                    statement1.executeUpdate(update);
                    JOptionPane.showMessageDialog(null, "User Updated");
                    this.dispose();
                    ReportSettingForm rsf = new ReportSettingForm();
                    rsf.userPopulate();
                }
            } catch (SQLException ex) {
                Logger.getLogger(UserUpdateForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Databse Connection Failed!!!");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPasswordField_pass_upFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pass_upFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pass_upFocusGained

    private void jPasswordField_pass_upKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pass_upKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pass_upKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(UserUpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        user_type_up.setSelectedItem(type_a);
        jTextField_userName_up.setText(user_a);
    }//GEN-LAST:event_formWindowOpened

    private void jPasswordField_pass_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_pass_upMouseClicked
        // TODO add your handling code here:
        jPasswordField_pass_up.setText("");
    }//GEN-LAST:event_jPasswordField_pass_upMouseClicked

    private void jPasswordField_pass_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_pass_newMouseClicked
        // TODO add your handling code here:
        jPasswordField_pass_new.setText("");
    }//GEN-LAST:event_jPasswordField_pass_newMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField_pass_new;
    private javax.swing.JPasswordField jPasswordField_pass_up;
    private javax.swing.JTextField jTextField_userName_up;
    private javax.swing.JComboBox<String> user_type_up;
    // End of variables declaration//GEN-END:variables
}
